package openpme.expressions.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.editor.runtime.cells.BigCellUtil;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.nodeEditor.cells.EditorCell_Error;

/*package*/ class Expression_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public Expression_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createAlternation_1ltshm_a();
  }

  private EditorCell createAlternation_1ltshm_a() {
    boolean alternationCondition = true;
    alternationCondition = nodeCondition_1ltshm_a0();
    EditorCell editorCell = null;
    if (alternationCondition) {
      editorCell = createError_1ltshm_a0();
    } else {
      editorCell = createComponent_1ltshm_a0();
    }
    EditorCell bigCell = BigCellUtil.findBigCell(editorCell, getNode());
    if (bigCell != null) {
      bigCell.setBig(true);
      bigCell.setCellContext(getCellFactory().getCellContext());
    }
    return editorCell;
  }
  private boolean nodeCondition_1ltshm_a0() {
    return SNodeOperations.getConcept(myNode).isAbstract();
  }
  private EditorCell createError_1ltshm_a0() {
    EditorCell_Error editorCell = new EditorCell_Error(getEditorContext(), myNode, "<expr>");
    editorCell.setCellId("Error_1ltshm_a0");
    return editorCell;
  }
  private EditorCell createComponent_1ltshm_a0() {
    EditorCell editorCell = getCellFactory().createEditorComponentCell(myNode, "jetbrains.mps.lang.core.editor.alias");
    return editorCell;
  }
}
