package main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.MappingScriptContext;

@Generated
public class QueriesGenerated {
  public static void mappingScript_CodeBlock_694935992172379340(final MappingScriptContext _context) {
  }
}
